---
abstract: 'Github v3 API'
author:
  - 'Johannes Plunien <plu@cpan.org>'
build_requires:
  File::Slurp: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pithub
requires:
  HTTP::Message: 0
  JSON::Any: 0
  JSON::XS: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Moose: 0
  MooseX::Role::BuildInstanceOf: 0
  MooseX::Types::URI: 0
  namespace::autoclean: 0
version: 0.01000
